POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "MNK",
    "number": "555-555-5555"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "name": "Merlin"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
    "number": "111-111-1111"
}

